Спринт 15
PolinaShmargunova/java-shareit pull request #3
Opened 2023-05-20 10:50 UTC by PolinaShmargunova

2023-05-20 12:07 UTC, PolinaShmargunova commented
IDEA показывает, что покрытие тестами составляет 93% построчно и 94% по методам, но jacoco не проходит проверку

2023-05-21 21:28 UTC, z8q requested changes

2023-05-21 21:28 UTC, z8q commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +public class BookingServiceTest {
Похоже не хватает выполнения одного пункта из тз:
`Реализовать тесты для слоя репозиториев вашего приложения с использованием аннотации @DataJpaTest.`
На класс ставится такая аннотация,
а на поля репозиториев ставим Autowired.
К классам репозиториев применится тестовая конфигурация,
Можно будет обычным образом вызывать методы репозиториев без when-then

2023-05-21 21:28 UTC, z8q commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    @Mock
Также не хватает тестов dto-классов с применением аннотации `@JsonTest`
Можно обсудить с наставником.
В тесте создается и автовайрится поле JacksonTester<YourExampleDto> jsonTester;

Далее создается Dto и отправляется в jsonTester.write(dto).
Метод write вернет экземпляр JsonContent, который через assert-ы можно попроверять:
как пример
assertThat(result).hasJsonPath("$.start");

2023-05-21 21:28 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemDto> searchItem(String text, long ownerId, Integer from, Integer size);
Во всех методах,  где применяется пагинация, нужно использовать в аргументах класс Pageable,
Для интерфейса Booking тоже такой же комментарий

2023-05-21 21:28 UTC, z8q commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    private BookingRepository bookingRepository;
Про интеграционные тесты можно тоже с наставником обсудить.  В коде не увидел

2023-05-23 19:39 UTC, z8q approved these changes

2023-05-27 10:14 UTC, merged